### ISSUE TITLE
i will facing some issues in angular 6 related to devenvmode problem. anyone its working ?

### ISSUE THREAD

**Issue by Sureshanbu** [annapogorelova/ng2-go-top-button#19]

**Comment by tsetiz** [comment]
I am also facing the same problem. Any updates going on for angular 6 ???

**Comment by annapogorelova** [comment]
Thanks all for letting me know, will see what might be causing the issue.

**Comment by ealib** [comment]
Same issue here, after migrating a project `from` Angular 5.2 to 6.0:

```sh
Date: 2018-05-19T12:25:39.202Z - Hash: 89be19a76a8aafe3b4d4 - Time: 1465ms
5 unchanged chunks
chunk {main} main.js, main.js.map (main) 346 kB [initial] [rendered]

WARNING in ./node_modules/ng2-go-top-button/node_modules/@angular/core/esm5/core.js
6570:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ng2-go-top-button/node_modules/@angular/core/esm5/core.js
6590:15-102 Critical dependency: the request of a dependency is an expression
i ｢wdm｣: Compiled with warnings.
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ng2-go-top-button/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ng2-go-top-button/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

```

**Comment by hristijan5** [comment]
Same problem with ng 6

**Comment by annapogorelova** [comment]
Hey, guys, I have just released [v6.0.0](https://github.com/annapogorelova/ng2-go-top-button/releases/tag/v6.0.0), this one should be fixed there, check it out.
